### PR TITLE
docs: add best practices to Agama-PW README

### PR DESCRIPTION
**Pull request by ossdhaval**
add best practices to Agama-PW README

### CODE REVIEW

**Review by jgomer2001 — CHANGES_REQUESTED** [review]
> steps listed ...

There is a period after the link and `to achieve these` afterwards. Is it another sentence?

> Agama flow can also call or trigger flows in the same or Agama projects to ...

Is it well-written?, not sure what you mean there

> use the Agama Lab

"use Agama Lab" ?

**Comment by ossdhaval** [comment]
> > steps listed ...
> 
> There is a period after the link and `to achieve these` afterwards. Is it another sentence?
> 
> > Agama flow can also call or trigger flows in the same or Agama projects to ...
> 
> Is it well-written?, not sure what you mean there
> 
> > use the Agama Lab
> 
> "use Agama Lab" ?

Fixed the first and last observation. 

About the second observation, I want to highlight the functionality enabled by the `trigger`. Like how a flow in `Agama-hello` project is calling(triggering) a flow from `Agama-openid` project. But if this meaning is not clear in the sentence, can you help me rephrase it?

**Comment by jgomer2001** [comment]
hello, I'd suggest this one:

`This  project can be re-used in other Agama projects to create more complex authentication journeys: trigger flow [org.gluu.agama.pw.main](#orggluuagamapwmain) where you see fit.`

**Comment by ossdhaval** [comment]
@jgomer2001 I have updated the text. Please review.

**Review by jgomer2001 — APPROVED** [review]

**Pull request merged**
